# Generated by Django 5.2 on 2025-09-12 00:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
