# Generated by Django 5.2 on 2025-09-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwt', '0003_creditcard_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ['-created_at']},
        ),
    ]
