# Generated by Django 5.2 on 2025-07-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_creatorprofile_profile_picture_creatorpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
